# --------------------------------------------
# SERVER CONFIGURATION
# --------------------------------------------
server:
  port: 8083


# --------------------------------------------
# ROUTING ACTUATOR CONFIGURATION 
# --------------------------------------------    
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway, health, info, env, metrics 
      base-path: /actuator

# --------------------------------------------
# LOG CONFIGURATION
# --------------------------------------------  
logging:
  level:
    org:
      springframework: INFO
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: ${spring.application.name}.log
  path: /var/log

# --------------------------------------------
# SPRING CONFIGURATION
# -------------------------------------------- 
spring:
  cloud:
    gateway:
        
# --------------------------------------------
# CORS CONFIGURATION
# --------------------------------------------
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: 
            - GET
   
# --------------------------------------------
# DISCOVERY CONFIGURATION
# --------------------------------------------
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# --------------------------------------------
# CLOUD ROUTES CONFIGURATION
# --------------------------------------------
      routes:
      - id: discovery
        uri: http://localhost:8082
        predicates:
        - Path=/eureka
        filters:
        - StripPrefix=1
      - id: discovery
        uri: http://localhost:8082/eureka/js/
        predicates:
        - Path=/eureka/js/**
      - id: discovery
        uri: http://localhost:8082/eureka/css/
        predicates:
        - Path=/eureka/css/** 
      - id: discovery
        uri: http://localhost:8082/eureka/images/
        predicates:
        - Path=/eureka/images/**
      - id: discovery
        uri: http://localhost:8082/eureka/fonts/
        predicates:
        - Path=/eureka/fonts/**
      - id: cloud-config
        uri: http://localhost:8080
        predicates:
        - Path=/api/config/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: hystrix
            fallbackUri: forward:/fallback/config
        
# --------------------------------------------
# MICROSERVICES ROUTES CONFIGURATION
# --------------------------------------------
      - id: login
        uri: http://localhost:8102
        predicates:
        - Path=/api/login/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: hystrix
            fallbackUri: forward:/fallback/microservices

          